/* THE CARD RENDERER'S COMPILED SHADERS (run hd2, lane GPU2; the edge
   smoothing pair added by run perf2, lane GPURB). GENERATED, not
   written by hand: this file is the byte-for-byte output of the Windows SDK's
   fxc.exe on hal/gpu_raster.hlsl, which is checked in beside it, with the /Fh
   outputs concatenated and "const BYTE" spelled as "static const unsigned
   char" so the header needs no windows.h and no linkage of its own.

   THE EXACT COMMAND LINES, run from the Windows SDK's own bin directory for
   the installed version, x86 flavour:

     fxc.exe /nologo /T vs_4_0 /E vs_main /O3 /Vn kGpuRasterVS /Fh <out> gpu_raster.hlsl
     fxc.exe /nologo /T ps_4_0 /E ps_main /O3 /Vn kGpuRasterPS /Fh <out> gpu_raster.hlsl
     fxc.exe /nologo /T vs_5_0 /E aa_vs /O3 /Vn kGpuAaVS /Fh <out> gpu_raster.hlsl
     fxc.exe /nologo /T ps_5_0 /E aa_ps /O3 /Vn kGpuAaPS /Fh <out> gpu_raster.hlsl
     fxc.exe /nologo /T ps_4_0 /E ps_filt /O3 /Vn kGpuRasterPSF /Fh <out> gpu_raster.hlsl

   (shader model 5 for the edge smoothing: it is the model that encodes
   `precise`, which that pass's exact arithmetic depends on). SDK 10.0.22621
   and 10.0.26100 give the same bytes.

   (the fifth, kGpuRasterPSF, was added by run hunt7 for TextureFilter 1 and 2
   and is appended last; the first four blocks are unchanged, and ps_main
   compiles to the identical bytes with the shared shade() helper in place)

   To regenerate: run those five, replace each "const BYTE" with "static const
   unsigned char", and paste the five blocks below in this order. Nothing in the
   build runs fxc, and d3dcompiler.dll is never loaded at run time.

   The #if 0 blocks are fxc's own report -- the resource bindings, the input
   and output signatures and the disassembly -- kept because they are the only
   readable description of what the bytes are. */
#ifndef PORT_GPU_RASTER_SHADERS_H
#define PORT_GPU_RASTER_SHADERS_H

#if 0
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
// COLOR                    0   xyz         2     NONE   float   xyz 
// TEXCOORD                 1   xy          3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
// COLOR                    0   xyz         2     NONE   float   xyz 
// TEXCOORD                 1   xy          3     NONE   float   xy  
//
vs_4_0
dcl_input v0.xyzw
dcl_input v1.xy
dcl_input v2.xyz
dcl_input v3.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
dcl_output o2.xyz
dcl_output o3.xy
mov o0.xyzw, v0.xyzw
mov o1.xy, v1.xyxx
mov o2.xyz, v2.xyzx
mov o3.xy, v3.xyxx
ret 
// Approximately 5 instruction slots used
#endif

static const unsigned char kGpuRasterVS[] =
{
     68,  88,  66,  67,  92, 122, 
     69,  72, 211, 250, 253, 138, 
    137, 169, 101,  37, 150, 254, 
    244, 196,   1,   0,   0,   0, 
    216,   2,   0,   0,   5,   0, 
      0,   0,  52,   0,   0,   0, 
    128,   0,   0,   0,   8,   1, 
      0,   0, 148,   1,   0,   0, 
     92,   2,   0,   0,  82,  68, 
     69,  70,  68,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     28,   0,   0,   0,   0,   4, 
    254, 255,   0, 129,   0,   0, 
     28,   0,   0,   0,  77, 105, 
     99, 114, 111, 115, 111, 102, 
    116,  32,  40,  82,  41,  32, 
     72,  76,  83,  76,  32,  83, 
    104,  97, 100, 101, 114,  32, 
     67, 111, 109, 112, 105, 108, 
    101, 114,  32,  49,  48,  46, 
     49,   0,  73,  83,  71,  78, 
    128,   0,   0,   0,   4,   0, 
      0,   0,   8,   0,   0,   0, 
    104,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0,  15,  15,   0,   0, 
    113,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      3,   0,   0,   0,   1,   0, 
      0,   0,   3,   3,   0,   0, 
    122,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      3,   0,   0,   0,   2,   0, 
      0,   0,   7,   7,   0,   0, 
    113,   0,   0,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
      3,   0,   0,   0,   3,   0, 
      0,   0,   3,   3,   0,   0, 
     80,  79,  83,  73,  84,  73, 
     79,  78,   0,  84,  69,  88, 
     67,  79,  79,  82,  68,   0, 
     67,  79,  76,  79,  82,   0, 
     79,  83,  71,  78, 132,   0, 
      0,   0,   4,   0,   0,   0, 
      8,   0,   0,   0, 104,   0, 
      0,   0,   0,   0,   0,   0, 
      1,   0,   0,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
     15,   0,   0,   0, 116,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,   1,   0,   0,   0, 
      3,  12,   0,   0, 125,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,   2,   0,   0,   0, 
      7,   8,   0,   0, 116,   0, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,   3,   0,   0,   0, 
      3,  12,   0,   0,  83,  86, 
     95,  80,  79,  83,  73,  84, 
     73,  79,  78,   0,  84,  69, 
     88,  67,  79,  79,  82,  68, 
      0,  67,  79,  76,  79,  82, 
      0, 171,  83,  72,  68,  82, 
    192,   0,   0,   0,  64,   0, 
      1,   0,  48,   0,   0,   0, 
     95,   0,   0,   3, 242,  16, 
     16,   0,   0,   0,   0,   0, 
     95,   0,   0,   3,  50,  16, 
     16,   0,   1,   0,   0,   0, 
     95,   0,   0,   3, 114,  16, 
     16,   0,   2,   0,   0,   0, 
     95,   0,   0,   3,  50,  16, 
     16,   0,   3,   0,   0,   0, 
    103,   0,   0,   4, 242,  32, 
     16,   0,   0,   0,   0,   0, 
      1,   0,   0,   0, 101,   0, 
      0,   3,  50,  32,  16,   0, 
      1,   0,   0,   0, 101,   0, 
      0,   3, 114,  32,  16,   0, 
      2,   0,   0,   0, 101,   0, 
      0,   3,  50,  32,  16,   0, 
      3,   0,   0,   0,  54,   0, 
      0,   5, 242,  32,  16,   0, 
      0,   0,   0,   0,  70,  30, 
     16,   0,   0,   0,   0,   0, 
     54,   0,   0,   5,  50,  32, 
     16,   0,   1,   0,   0,   0, 
     70,  16,  16,   0,   1,   0, 
      0,   0,  54,   0,   0,   5, 
    114,  32,  16,   0,   2,   0, 
      0,   0,  70,  18,  16,   0, 
      2,   0,   0,   0,  54,   0, 
      0,   5,  50,  32,  16,   0, 
      3,   0,   0,   0,  70,  16, 
     16,   0,   3,   0,   0,   0, 
     62,   0,   0,   1,  83,  84, 
     65,  84, 116,   0,   0,   0, 
      5,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      8,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   4,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0
};

#if 0
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer ToonTable
// {
//
//   float4 toon[32];                   // Offset:    0 Size:   512
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// smp0                              sampler      NA          NA             s0      1 
// tex0                              texture  float4          2d             t0      1 
// ToonTable                         cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
// COLOR                    0   xyz         2     NONE   float   xyz 
// TEXCOORD                 1   xy          3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
// SV_TARGET                1   x           1   TARGET    uint   x   
//
ps_4_0
dcl_constantbuffer CB0[32], dynamicIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_input_ps linear noperspective v2.xyz
dcl_input_ps constant v3.xy
dcl_output o0.xyzw
dcl_output o1.x
dcl_temps 4
sample r0.xyzw, v1.xyxx, t0.xyzw, s0
mad r0.w, r0.w, l(255.000000), l(0.500000)
round_ni r0.w, r0.w
add r1.x, r0.w, l(-0.500000)
lt r1.x, r1.x, l(0.000000)
discard_nz r1.x
mad r0.w, v3.x, r0.w, l(127.000000)
mul r0.w, r0.w, l(0.003922)
add r1.x, v3.y, l(0.500000)
ftou r1.x, r1.x
ushr r1.y, r1.x, l(6)
if_nz r1.y
  mad r1.z, v2.x, l(0.121569), l(0.500000)
  ftoi r1.z, r1.z
  imax r1.z, r1.z, l(0)
  imin r1.z, r1.z, l(31)
  ieq r1.w, r1.y, l(1)
  movc r2.xyz, r1.wwww, cb0[r1.z + 0].xyzx, v2.xxxx
  mov r3.xyz, cb0[r1.z + 0].xyzx
else 
  mov r2.xyz, v2.xyzx
  mov r3.xyz, l(0,0,0,0)
endif 
mad r0.xyz, r2.xyzx, r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
round_ni r0.xyzw, r0.xyzw
ieq r1.y, r1.y, l(2)
add r2.xyz, r3.xyzx, r0.xyzx
movc r0.xyz, r1.yyyy, r2.xyzx, r0.xyzx
max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r0.xyz, r0.xyzx, l(255.000000, 255.000000, 255.000000, 0.000000)
mul o0.xyz, r0.xyzx, l(0.003922, 0.003922, 0.003922, 0.000000)
min r0.x, r0.w, l(31.000000)
mul o0.w, r0.x, l(0.032258)
and r0.x, r1.x, l(63)
iadd o1.x, r0.x, l(128)
ret 
// Approximately 36 instruction slots used
#endif

static const unsigned char kGpuRasterPS[] =
{
     68,  88,  66,  67,  32, 164, 
    194, 116, 161, 248,  33, 139, 
     20, 147, 238,  24,  64, 125, 
     34, 158,   1,   0,   0,   0, 
    228,   6,   0,   0,   5,   0, 
      0,   0,  52,   0,   0,   0, 
     60,   1,   0,   0, 200,   1, 
      0,   0,  20,   2,   0,   0, 
    104,   6,   0,   0,  82,  68, 
     69,  70,   0,   1,   0,   0, 
      1,   0,   0,   0, 144,   0, 
      0,   0,   3,   0,   0,   0, 
     28,   0,   0,   0,   0,   4, 
    255, 255,   0, 129,   0,   0, 
    216,   0,   0,   0, 124,   0, 
      0,   0,   3,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   1,   0,   0,   0, 
    129,   0,   0,   0,   2,   0, 
      0,   0,   5,   0,   0,   0, 
      4,   0,   0,   0, 255, 255, 
    255, 255,   0,   0,   0,   0, 
      1,   0,   0,   0,  13,   0, 
      0,   0, 134,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      1,   0,   0,   0, 115, 109, 
    112,  48,   0, 116, 101, 120, 
     48,   0,  84, 111, 111, 110, 
     84,  97,  98, 108, 101,   0, 
    134,   0,   0,   0,   1,   0, 
      0,   0, 168,   0,   0,   0, 
      0,   2,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
    192,   0,   0,   0,   0,   0, 
      0,   0,   0,   2,   0,   0, 
      2,   0,   0,   0, 200,   0, 
      0,   0,   0,   0,   0,   0, 
    116, 111, 111, 110,   0, 171, 
    171, 171,   1,   0,   3,   0, 
      1,   0,   4,   0,  32,   0, 
      0,   0,   0,   0,   0,   0, 
     77, 105,  99, 114, 111, 115, 
    111, 102, 116,  32,  40,  82, 
     41,  32,  72,  76,  83,  76, 
     32,  83, 104,  97, 100, 101, 
    114,  32,  67, 111, 109, 112, 
    105, 108, 101, 114,  32,  49, 
     48,  46,  49,   0,  73,  83, 
     71,  78, 132,   0,   0,   0, 
      4,   0,   0,   0,   8,   0, 
      0,   0, 104,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   3,   0,   0,   0, 
      0,   0,   0,   0,  15,   0, 
      0,   0, 116,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   3,   0,   0,   0, 
      1,   0,   0,   0,   3,   3, 
      0,   0, 125,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   3,   0,   0,   0, 
      2,   0,   0,   0,   7,   7, 
      0,   0, 116,   0,   0,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0,   3,   0,   0,   0, 
      3,   0,   0,   0,   3,   3, 
      0,   0,  83,  86,  95,  80, 
     79,  83,  73,  84,  73,  79, 
     78,   0,  84,  69,  88,  67, 
     79,  79,  82,  68,   0,  67, 
     79,  76,  79,  82,   0, 171, 
     79,  83,  71,  78,  68,   0, 
      0,   0,   2,   0,   0,   0, 
      8,   0,   0,   0,  56,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
     15,   0,   0,   0,  56,   0, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   1,   0,   0,   0, 
      1,  14,   0,   0,  83,  86, 
     95,  84,  65,  82,  71,  69, 
     84,   0, 171, 171,  83,  72, 
     68,  82,  76,   4,   0,   0, 
     64,   0,   0,   0,  19,   1, 
      0,   0,  89,   8,   0,   4, 
     70, 142,  32,   0,   0,   0, 
      0,   0,  32,   0,   0,   0, 
     90,   0,   0,   3,   0,  96, 
     16,   0,   0,   0,   0,   0, 
     88,  24,   0,   4,   0, 112, 
     16,   0,   0,   0,   0,   0, 
     85,  85,   0,   0,  98,  16, 
      0,   3,  50,  16,  16,   0, 
      1,   0,   0,   0,  98,  32, 
      0,   3, 114,  16,  16,   0, 
      2,   0,   0,   0,  98,   8, 
      0,   3,  50,  16,  16,   0, 
      3,   0,   0,   0, 101,   0, 
      0,   3, 242,  32,  16,   0, 
      0,   0,   0,   0, 101,   0, 
      0,   3,  18,  32,  16,   0, 
      1,   0,   0,   0, 104,   0, 
      0,   2,   4,   0,   0,   0, 
     69,   0,   0,   9, 242,   0, 
     16,   0,   0,   0,   0,   0, 
     70,  16,  16,   0,   1,   0, 
      0,   0,  70, 126,  16,   0, 
      0,   0,   0,   0,   0,  96, 
     16,   0,   0,   0,   0,   0, 
     50,   0,   0,   9, 130,   0, 
     16,   0,   0,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0, 127,  67,   1,  64, 
      0,   0,   0,   0,   0,  63, 
     65,   0,   0,   5, 130,   0, 
     16,   0,   0,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,   0,   0,   0,   7, 
     18,   0,  16,   0,   1,   0, 
      0,   0,  58,   0,  16,   0, 
      0,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0, 191, 
     49,   0,   0,   7,  18,   0, 
     16,   0,   1,   0,   0,   0, 
     10,   0,  16,   0,   1,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,  13,   0, 
      4,   3,  10,   0,  16,   0, 
      1,   0,   0,   0,  50,   0, 
      0,   9, 130,   0,  16,   0, 
      0,   0,   0,   0,  10,  16, 
     16,   0,   3,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0, 254,  66,  56,   0, 
      0,   7, 130,   0,  16,   0, 
      0,   0,   0,   0,  58,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0, 129, 128, 
    128,  59,   0,   0,   0,   7, 
     18,   0,  16,   0,   1,   0, 
      0,   0,  26,  16,  16,   0, 
      3,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,  63, 
     28,   0,   0,   5,  18,   0, 
     16,   0,   1,   0,   0,   0, 
     10,   0,  16,   0,   1,   0, 
      0,   0,  85,   0,   0,   7, 
     34,   0,  16,   0,   1,   0, 
      0,   0,  10,   0,  16,   0, 
      1,   0,   0,   0,   1,  64, 
      0,   0,   6,   0,   0,   0, 
     31,   0,   4,   3,  26,   0, 
     16,   0,   1,   0,   0,   0, 
     50,   0,   0,   9,  66,   0, 
     16,   0,   1,   0,   0,   0, 
     10,  16,  16,   0,   2,   0, 
      0,   0,   1,  64,   0,   0, 
    249, 248, 248,  61,   1,  64, 
      0,   0,   0,   0,   0,  63, 
     27,   0,   0,   5,  66,   0, 
     16,   0,   1,   0,   0,   0, 
     42,   0,  16,   0,   1,   0, 
      0,   0,  36,   0,   0,   7, 
     66,   0,  16,   0,   1,   0, 
      0,   0,  42,   0,  16,   0, 
      1,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,   0, 
     37,   0,   0,   7,  66,   0, 
     16,   0,   1,   0,   0,   0, 
     42,   0,  16,   0,   1,   0, 
      0,   0,   1,  64,   0,   0, 
     31,   0,   0,   0,  32,   0, 
      0,   7, 130,   0,  16,   0, 
      1,   0,   0,   0,  26,   0, 
     16,   0,   1,   0,   0,   0, 
      1,  64,   0,   0,   1,   0, 
      0,   0,  55,   0,   0,  11, 
    114,   0,  16,   0,   2,   0, 
      0,   0, 246,  15,  16,   0, 
      1,   0,   0,   0,  70, 130, 
     32,   4,   0,   0,   0,   0, 
     42,   0,  16,   0,   1,   0, 
      0,   0,   6,  16,  16,   0, 
      2,   0,   0,   0,  54,   0, 
      0,   7, 114,   0,  16,   0, 
      3,   0,   0,   0,  70, 130, 
     32,   4,   0,   0,   0,   0, 
     42,   0,  16,   0,   1,   0, 
      0,   0,  18,   0,   0,   1, 
     54,   0,   0,   5, 114,   0, 
     16,   0,   2,   0,   0,   0, 
     70,  18,  16,   0,   2,   0, 
      0,   0,  54,   0,   0,   8, 
    114,   0,  16,   0,   3,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  21,   0, 
      0,   1,  50,   0,   0,  12, 
    114,   0,  16,   0,   0,   0, 
      0,   0,  70,   2,  16,   0, 
      2,   0,   0,   0,  70,   2, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0,  63,   0,   0,   0,  63, 
      0,   0,   0,  63,   0,   0, 
      0,   0,  65,   0,   0,   5, 
    242,   0,  16,   0,   0,   0, 
      0,   0,  70,  14,  16,   0, 
      0,   0,   0,   0,  32,   0, 
      0,   7,  34,   0,  16,   0, 
      1,   0,   0,   0,  26,   0, 
     16,   0,   1,   0,   0,   0, 
      1,  64,   0,   0,   2,   0, 
      0,   0,   0,   0,   0,   7, 
    114,   0,  16,   0,   2,   0, 
      0,   0,  70,   2,  16,   0, 
      3,   0,   0,   0,  70,   2, 
     16,   0,   0,   0,   0,   0, 
     55,   0,   0,   9, 114,   0, 
     16,   0,   0,   0,   0,   0, 
     86,   5,  16,   0,   1,   0, 
      0,   0,  70,   2,  16,   0, 
      2,   0,   0,   0,  70,   2, 
     16,   0,   0,   0,   0,   0, 
     52,   0,   0,  10, 114,   0, 
     16,   0,   0,   0,   0,   0, 
     70,   2,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  51,   0, 
      0,  10, 114,   0,  16,   0, 
      0,   0,   0,   0,  70,   2, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
    127,  67,   0,   0, 127,  67, 
      0,   0, 127,  67,   0,   0, 
      0,   0,  56,   0,   0,  10, 
    114,  32,  16,   0,   0,   0, 
      0,   0,  70,   2,  16,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0, 129, 128, 128,  59, 
    129, 128, 128,  59, 129, 128, 
    128,  59,   0,   0,   0,   0, 
     51,   0,   0,   7,  18,   0, 
     16,   0,   0,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0, 248,  65,  56,   0, 
      0,   7, 130,  32,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0,   8,  33, 
      4,  61,   1,   0,   0,   7, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      1,   0,   0,   0,   1,  64, 
      0,   0,  63,   0,   0,   0, 
     30,   0,   0,   7,  18,  32, 
     16,   0,   1,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
    128,   0,   0,   0,  62,   0, 
      0,   1,  83,  84,  65,  84, 
    116,   0,   0,   0,  36,   0, 
      0,   0,   4,   0,   0,   0, 
      0,   0,   0,   0,   5,   0, 
      0,   0,  16,   0,   0,   0, 
      5,   0,   0,   0,   2,   0, 
      0,   0,   2,   0,   0,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   3,   0,   0,   0, 
      2,   0,   0,   0,   4,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0
};

#if 0
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_VertexID              0   x           0   VERTID    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_input_sgv v0.x, vertex_id
dcl_output_siv o0.xyzw, position
dcl_temps 1
ieq r0.xy, v0.xxxx, l(1, 2, 0, 0)
movc o0.xy, r0.xyxx, l(3.000000,-3.000000,0,0), l(-1.000000,1.000000,0,0)
mov o0.zw, l(0,0,0,1.000000)
ret 
// Approximately 4 instruction slots used
#endif

static const unsigned char kGpuAaVS[] =
{
     68,  88,  66,  67, 221, 168, 
    185, 122,  34, 249,  98, 194, 
     91,   4,   9, 110, 197,  36, 
     52,  86,   1,   0,   0,   0, 
    104,   2,   0,   0,   5,   0, 
      0,   0,  52,   0,   0,   0, 
    160,   0,   0,   0, 212,   0, 
      0,   0,   8,   1,   0,   0, 
    204,   1,   0,   0,  82,  68, 
     69,  70, 100,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     60,   0,   0,   0,   0,   5, 
    254, 255,   0, 129,   0,   0, 
     60,   0,   0,   0,  82,  68, 
     49,  49,  60,   0,   0,   0, 
     24,   0,   0,   0,  32,   0, 
      0,   0,  40,   0,   0,   0, 
     36,   0,   0,   0,  12,   0, 
      0,   0,   0,   0,   0,   0, 
     77, 105,  99, 114, 111, 115, 
    111, 102, 116,  32,  40,  82, 
     41,  32,  72,  76,  83,  76, 
     32,  83, 104,  97, 100, 101, 
    114,  32,  67, 111, 109, 112, 
    105, 108, 101, 114,  32,  49, 
     48,  46,  49,   0,  73,  83, 
     71,  78,  44,   0,   0,   0, 
      1,   0,   0,   0,   8,   0, 
      0,   0,  32,   0,   0,   0, 
      0,   0,   0,   0,   6,   0, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0,   1,   1, 
      0,   0,  83,  86,  95,  86, 
    101, 114, 116, 101, 120,  73, 
     68,   0,  79,  83,  71,  78, 
     44,   0,   0,   0,   1,   0, 
      0,   0,   8,   0,   0,   0, 
     32,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0,  15,   0,   0,   0, 
     83,  86,  95,  80, 111, 115, 
    105, 116, 105, 111, 110,   0, 
     83,  72,  69,  88, 188,   0, 
      0,   0,  80,   0,   1,   0, 
     47,   0,   0,   0, 106,   8, 
      0,   1,  96,   0,   0,   4, 
     18,  16,  16,   0,   0,   0, 
      0,   0,   6,   0,   0,   0, 
    103,   0,   0,   4, 242,  32, 
     16,   0,   0,   0,   0,   0, 
      1,   0,   0,   0, 104,   0, 
      0,   2,   1,   0,   0,   0, 
     32,   0,   0,  10,  50,   0, 
     16,   0,   0,   0,   0,   0, 
      6,  16,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      1,   0,   0,   0,   2,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  55,   0, 
      0,  15,  50,  32,  16,   0, 
      0,   0,   0,   0,  70,   0, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
     64,  64,   0,   0,  64, 192, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0, 128, 191,   0,   0, 
    128,  63,   0,   0,   0,   0, 
      0,   0,   0,   0,  54,   0, 
      0,   8, 194,  32,  16,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0, 128,  63, 
     62,   0,   0,   1,  83,  84, 
     65,  84, 148,   0,   0,   0, 
      4,   0,   0,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
      2,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0
};

#if 0
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// aa_src                            texture    uint          2d             t0      1 
// aa_cov                            texture    uint          2d             t1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   x           0   TARGET    uint   x   
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_texture2d (uint,uint,uint,uint) t0
dcl_resource_texture2d (uint,uint,uint,uint) t1
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_output o0.x
dcl_temps 10
ftoi [precise(xy)] r0.xy, v0.xyxx
mov [precise(z)] r0.z, l(0)
ld_indexable [precise(x)](texture2d)(uint,uint,uint,uint) r1.x, r0.xyzz, t0.xyzw
ld_indexable [precise(y)](texture2d)(uint,uint,uint,uint) r1.y, r0.xyzz, t1.yxzw
if_z r1.y
  mov [precise(x)] o0.x, r1.x
  ret 
endif 
resinfo_indexable [precise(yz)](texture2d)(uint,uint,uint,uint) r1.yz, l(0), t0.zxyw
ftoi [precise(yz)] r1.yz, r1.yyzy
ilt [precise(xy)] r2.xy, l(0, 0, 0, 0), r0.xyxx
iadd [precise] r3.xyzw, r0.xxyy, l(-1, 1, -1, 1)
ilt [precise(yz)] r1.yz, r3.yywy, r1.yyzy
and [precise(xz)] r2.xz, r2.xxyx, r3.xxzx
iadd [precise(xy)] r3.xy, r0.xyxx, -r1.yzyy
mov [precise(w)] r0.w, r2.z
ld_indexable [precise(w)](texture2d)(uint,uint,uint,uint) r0.w, r0.xwzz, t0.yzwx
mov [precise(zw)] r3.zw, r0.xxxz
ld_indexable [precise(x)](texture2d)(uint,uint,uint,uint) r0.x, r3.zyww, t0.xyzw
mov [precise(yw)] r2.yw, r0.yyyz
ld_indexable [precise(y)](texture2d)(uint,uint,uint,uint) r0.y, r2.xyww, t0.yxzw
mov [precise(xzw)] r2.xzw, r3.xxww
ld_indexable [precise(z)](texture2d)(uint,uint,uint,uint) r0.z, r2.xyzw, t0.yzxw
ubfe [precise(yz)] r1.yz, l(0, 8, 8, 0), l(0, 16, 8, 0), r1.xxxx
and [precise(w)] r1.w, r1.x, l(255)
utof [precise(yzw)] r1.yzw, r1.yyzw
mul [precise(xy)] r2.xy, r1.yzyy, l(0.299000, 0.587000, 0.000000, 0.000000)
add [precise(x)] r2.x, r2.y, r2.x
mul [precise(y)] r2.y, r1.w, l(0.114000)
add [precise(x)] r2.x, r2.y, r2.x
ubfe [precise(yz)] r2.yz, l(0, 8, 8, 0), l(0, 16, 8, 0), r0.wwww
and [precise(w)] r2.w, r0.w, l(255)
utof [precise(yzw)] r2.yzw, r2.yyzw
mul [precise(yz)] r2.yz, r2.yyzy, l(0.000000, 0.299000, 0.587000, 0.000000)
add [precise(y)] r2.y, r2.z, r2.y
mul [precise(z)] r2.z, r2.w, l(0.114000)
add [precise(y)] r2.y, r2.z, r2.y
ubfe [precise(zw)] r2.zw, l(0, 0, 8, 8), l(0, 0, 16, 8), r0.xxxx
utof [precise(zw)] r2.zw, r2.zzzw
and [precise(xz)] r3.xz, r0.xxzx, l(255, 0, 255, 0)
utof [precise(x)] r3.x, r3.x
mul [precise(zw)] r2.zw, r2.zzzw, l(0.000000, 0.000000, 0.299000, 0.587000)
add [precise(z)] r2.z, r2.w, r2.z
mul [precise(w)] r2.w, r3.x, l(0.114000)
add [precise(z)] r2.z, r2.w, r2.z
ubfe [precise(xy)] r3.xy, l(8, 8, 0, 0), l(16, 8, 0, 0), r0.yyyy
utof [precise(xy)] r3.xy, r3.xyxx
and [precise(w)] r2.w, r0.y, l(255)
utof [precise(w)] r2.w, r2.w
mul [precise(xy)] r3.xy, r3.xyxx, l(0.299000, 0.587000, 0.000000, 0.000000)
add [precise(x)] r3.x, r3.y, r3.x
mul [precise(w)] r2.w, r2.w, l(0.114000)
add [precise(w)] r2.w, r2.w, r3.x
ubfe [precise(xy)] r3.xy, l(8, 8, 0, 0), l(16, 8, 0, 0), r0.zzzz
utof [precise(xyz)] r3.xyz, r3.xyzx
mul [precise(xy)] r3.xy, r3.xyxx, l(0.299000, 0.587000, 0.000000, 0.000000)
add [precise(x)] r3.x, r3.y, r3.x
mul [precise(y)] r3.y, r3.z, l(0.114000)
add [precise(x)] r3.x, r3.y, r3.x
min [precise(y)] r3.y, r2.y, r2.x
min [precise(y)] r3.y, r2.z, r3.y
min [precise(y)] r3.y, r2.w, r3.y
min [precise(y)] r3.y, r3.x, r3.y
max [precise(z)] r3.z, r2.y, r2.x
max [precise(z)] r3.z, r2.z, r3.z
max [precise(z)] r3.z, r2.w, r3.z
max [precise(z)] r3.z, r3.x, r3.z
add [precise(y)] r3.y, -r3.y, r3.z
mul [precise(z)] r3.z, r3.z, l(0.125000)
lt [precise(w)] r3.w, r3.y, l(8.000000)
lt [precise(z)] r3.z, r3.y, r3.z
or [precise(z)] r3.z, r3.z, r3.w
if_nz r3.z
  mov [precise(x)] o0.x, r1.x
  ret 
endif 
add [precise(y)] r2.y, r2.z, r2.y
add [precise(z)] r2.z, r2.w, r2.y
add [precise(z)] r2.z, r3.x, r2.z
mul [precise(z)] r2.z, r2.z, l(0.250000)
add [precise(z)] r2.z, -r2.x, r2.z
ne [precise(z)] r3.z, |r2.z|, l(0.000000)
if_nz r3.z
  div [precise(x)] r4.x, |r2.z|, r3.y
  iadd [precise] r5.xyzw, r4.xxxx, l(-1, -3, 1, -2)
  mul [precise] r6.xyzw, r3.yyyy, r5.ywxz
  mul [precise] r7.xyzw, r5.ywxz, l(4097.000000, 4097.000000, 4097.000000, 4097.000000)
  add [precise] r8.xyzw, -r5.ywxz, r7.xyzw
  add [precise] r7.xyzw, r7.xyzw, -r8.xyzw
  add [precise] r8.xyzw, r5.ywxz, -r7.xyzw
  mul [precise(z)] r3.z, r3.y, l(4097.000000)
  add [precise(w)] r3.w, -r3.y, r3.z
  add [precise(z)] r3.z, -r3.w, r3.z
  add [precise(w)] r3.w, -r3.z, r3.y
  mul [precise] r9.xyzw, r3.zzzz, r7.xyzw
  add [precise] r9.xyzw, -r6.xyzw, r9.xyzw
  mul [precise] r7.xyzw, r3.wwww, r7.xyzw
  add [precise] r7.xyzw, r7.xyzw, r9.xyzw
  mul [precise] r9.xyzw, r3.zzzz, r8.xyzw
  add [precise] r7.xyzw, r7.xyzw, r9.xyzw
  mul [precise] r8.xyzw, r3.wwww, r8.xyzw
  add [precise] r7.xyzw, r7.xyzw, r8.xyzw
  add [precise] r6.xyzw, |r2.zzzz|, -r6.xyzw
  add [precise] r6.xyzw, -r7.xyzw, r6.xyzw
  lt [precise(w)] r4.w, |r6.x|, l(1000000015047466219876688855040.000000)
  mov [precise(xz)] r7.xz, r5.yywy
  mov [precise(yw)] r7.yw, |r6.xxxy|
  mov [precise(y)] r4.y, l(1000000015047466219876688855040.000000)
  movc [precise(yw)] r4.yw, r4.wwww, r7.xxxy, r4.xxxy
  lt [precise(x)] r6.x, |r6.y|, r4.w
  movc [precise(yw)] r4.yw, r6.xxxx, r7.zzzw, r4.yyyw
  lt [precise(x)] r6.x, |r6.z|, r4.w
  mov [precise(yw)] r5.yw, |r6.zzzw|
  movc [precise(yw)] r4.yw, r6.xxxx, r5.xxxy, r4.yyyw
  mul [precise(x)] r5.x, r3.y, r4.x
  mul [precise(y)] r5.y, r4.x, l(4097.000000)
  add [precise(x)] r6.x, -r4.x, r5.y
  add [precise(y)] r5.y, r5.y, -r6.x
  add [precise(x)] r6.x, r4.x, -r5.y
  mul [precise(y)] r6.y, r3.z, r5.y
  add [precise(y)] r6.y, -r5.x, r6.y
  mul [precise(y)] r5.y, r3.w, r5.y
  add [precise(y)] r5.y, r5.y, r6.y
  mul [precise(y)] r6.y, r3.z, r6.x
  add [precise(y)] r5.y, r5.y, r6.y
  mul [precise(x)] r6.x, r3.w, r6.x
  add [precise(y)] r5.y, r5.y, r6.x
  add [precise(x)] r5.x, |r2.z|, -r5.x
  add [precise(x)] r5.x, -r5.y, r5.x
  mov [precise(z)] r4.z, |r5.x|
  lt [precise(x)] r5.x, r4.z, r4.w
  movc [precise(yz)] r4.yz, r5.xxxx, r4.xxzx, r4.yywy
  lt [precise(w)] r4.w, |r6.w|, r4.z
  movc [precise(yz)] r4.yz, r4.wwww, r5.zzwz, r4.yyzy
  iadd [precise(xy)] r5.xy, r4.xxxx, l(2, 3, 0, 0)
  mul [precise(xw)] r4.xw, r3.yyyy, r5.xxxy
  mul [precise(xy)] r6.xy, r5.xyxx, l(4097.000000, 4097.000000, 0.000000, 0.000000)
  add [precise(zw)] r6.zw, -r5.xxxy, r6.xxxy
  add [precise(xy)] r6.xy, -r6.zwzz, r6.xyxx
  add [precise(zw)] r6.zw, r5.xxxy, -r6.xxxy
  mul [precise(xy)] r7.xy, r3.zzzz, r6.xyxx
  add [precise(xy)] r7.xy, -r4.xwxx, r7.xyxx
  mul [precise(xy)] r6.xy, r3.wwww, r6.xyxx
  add [precise(xy)] r6.xy, r6.xyxx, r7.xyxx
  mul [precise(yz)] r3.yz, r3.zzzz, r6.zzwz
  add [precise(yz)] r3.yz, r3.yyzy, r6.xxyx
  mul [precise(xy)] r6.xy, r3.wwww, r6.zwzz
  add [precise(yz)] r3.yz, r3.yyzy, r6.xxyx
  add [precise(xw)] r4.xw, |r2.zzzz|, -r4.xxxw
  add [precise(yz)] r3.yz, -r3.yyzy, r4.xxwx
  mov [precise(zw)] r5.zw, |r3.yyyz|
  lt [precise(z)] r2.z, r5.z, r4.z
  movc [precise(yz)] r3.yz, r2.zzzz, r5.xxzx, r4.yyzy
  lt [precise(z)] r2.z, r5.w, r3.z
  movc [precise(z)] r2.z, r2.z, r5.y, r3.y
else 
  mov [precise(z)] r2.z, l(0)
endif 
mul [precise(z)] r2.z, r2.z, r2.z
lt [precise(y)] r3.y, l(0.500000), r2.z
movc [precise(z)] r2.z, r3.y, l(0.500000), r2.z
ge [precise(y)] r3.y, l(0.002000), r2.z
if_nz r3.y
  mov [precise(x)] o0.x, r1.x
  ret 
endif 
add [precise(x)] r1.x, r2.w, r3.x
mul [precise(x)] r2.x, r2.x, l(2.000000)
add [precise(x)] r1.x, r1.x, -r2.x
add [precise(x)] r2.x, -r2.x, r2.y
ge [precise(x)] r1.x, |r1.x|, |r2.x|
movc [precise(xy)] r0.xy, r1.xxxx, r0.zyzz, r0.xwxx
ubfe [precise(zw)] r0.zw, l(0, 0, 8, 8), l(0, 0, 16, 8), r0.yyyy
ubfe [precise(xy)] r2.xy, l(8, 8, 0, 0), l(16, 8, 0, 0), r0.xxxx
utof [precise(zw)] r0.zw, r0.zzzw
mul [precise(zw)] r0.zw, r0.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000)
utof [precise(xy)] r2.xy, r2.xyxx
mul [precise(xy)] r2.xy, r2.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
add [precise(zw)] r0.zw, r0.zzzw, r2.xxxy
add [precise(zw)] r0.zw, r0.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000)
ftoi [precise(zw)] r0.zw, r0.zzzw
ishl [precise(zw)] r0.zw, r0.zzzw, l(0, 0, 16, 8)
iadd [precise(z)] r0.z, r0.z, l(0xff000000)
iadd [precise(w)] r0.w, r0.z, r0.w
and [precise(xy)] r0.xy, r0.xyxx, l(255, 255, 0, 0)
utof [precise(xy)] r0.xy, r0.xyxx
mul [precise(xy)] r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
add [precise(x)] r0.x, r0.x, r0.y
add [precise(x)] r0.x, r0.x, l(0.500000)
ftoi [precise(x)] r0.x, r0.x
iadd [precise(x)] r0.x, r0.w, r0.x
add [precise(y)] r0.y, -r2.z, l(1.000000)
ubfe [precise(zw)] r0.zw, l(0, 0, 8, 8), l(0, 0, 16, 8), r0.zzzw
mul [precise(xy)] r1.xy, r0.yyyy, r1.yzyy
utof [precise(zw)] r0.zw, r0.zzzw
mul [precise(zw)] r0.zw, r2.zzzz, r0.zzzw
add [precise(zw)] r0.zw, r0.zzzw, r1.xxxy
add [precise(zw)] r0.zw, r0.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000)
ftoi r0.zw, r0.zzzw
imax r0.zw, r0.zzzw, l(0, 0, 0, 0)
imin r0.zw, r0.zzzw, l(0, 0, 255, 255)
ishl r0.zw, r0.zzzw, l(0, 0, 16, 8)
iadd r0.z, r0.z, l(0xff000000)
iadd r0.z, r0.z, r0.w
and [precise(x)] r0.x, r0.x, l(255)
mul [precise(y)] r0.y, r0.y, r1.w
utof [precise(x)] r0.x, r0.x
mul [precise(x)] r0.x, r2.z, r0.x
add [precise(x)] r0.x, r0.x, r0.y
add [precise(x)] r0.x, r0.x, l(0.500000)
ftoi r0.x, r0.x
imax r0.x, r0.x, l(0)
imin r0.x, r0.x, l(255)
iadd o0.x, r0.z, r0.x
ret 
// Approximately 215 instruction slots used
#endif

static const unsigned char kGpuAaPS[] =
{
     68,  88,  66,  67,  30,  93, 
    196, 192, 119,  28,  55, 117, 
     92,  38, 178, 169, 228,  32, 
     23,  59,   1,   0,   0,   0, 
    224,  26,   0,   0,   5,   0, 
      0,   0,  52,   0,   0,   0, 
    240,   0,   0,   0,  36,   1, 
      0,   0,  88,   1,   0,   0, 
     68,  26,   0,   0,  82,  68, 
     69,  70, 180,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   2,   0,   0,   0, 
     60,   0,   0,   0,   0,   5, 
    255, 255,   0, 129,   0,   0, 
    138,   0,   0,   0,  82,  68, 
     49,  49,  60,   0,   0,   0, 
     24,   0,   0,   0,  32,   0, 
      0,   0,  40,   0,   0,   0, 
     36,   0,   0,   0,  12,   0, 
      0,   0,   0,   0,   0,   0, 
    124,   0,   0,   0,   2,   0, 
      0,   0,   4,   0,   0,   0, 
      4,   0,   0,   0, 255, 255, 
    255, 255,   0,   0,   0,   0, 
      1,   0,   0,   0,   1,   0, 
      0,   0, 131,   0,   0,   0, 
      2,   0,   0,   0,   4,   0, 
      0,   0,   4,   0,   0,   0, 
    255, 255, 255, 255,   1,   0, 
      0,   0,   1,   0,   0,   0, 
      1,   0,   0,   0,  97,  97, 
     95, 115, 114,  99,   0,  97, 
     97,  95,  99, 111, 118,   0, 
     77, 105,  99, 114, 111, 115, 
    111, 102, 116,  32,  40,  82, 
     41,  32,  72,  76,  83,  76, 
     32,  83, 104,  97, 100, 101, 
    114,  32,  67, 111, 109, 112, 
    105, 108, 101, 114,  32,  49, 
     48,  46,  49,   0, 171, 171, 
     73,  83,  71,  78,  44,   0, 
      0,   0,   1,   0,   0,   0, 
      8,   0,   0,   0,  32,   0, 
      0,   0,   0,   0,   0,   0, 
      1,   0,   0,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
     15,   3,   0,   0,  83,  86, 
     95,  80, 111, 115, 105, 116, 
    105, 111, 110,   0,  79,  83, 
     71,  78,  44,   0,   0,   0, 
      1,   0,   0,   0,   8,   0, 
      0,   0,  32,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0,   1,  14, 
      0,   0,  83,  86,  95,  84, 
     97, 114, 103, 101, 116,   0, 
    171, 171,  83,  72,  69,  88, 
    228,  24,   0,   0,  80,   0, 
      0,   0,  57,   6,   0,   0, 
    106,   8,   0,   1,  88,  24, 
      0,   4,   0, 112,  16,   0, 
      0,   0,   0,   0,  68,  68, 
      0,   0,  88,  24,   0,   4, 
      0, 112,  16,   0,   1,   0, 
      0,   0,  68,  68,   0,   0, 
    100,  32,   0,   4,  50,  16, 
     16,   0,   0,   0,   0,   0, 
      1,   0,   0,   0, 101,   0, 
      0,   3,  18,  32,  16,   0, 
      0,   0,   0,   0, 104,   0, 
      0,   2,  10,   0,   0,   0, 
     27,   0,  24,   5,  50,   0, 
     16,   0,   0,   0,   0,   0, 
     70,  16,  16,   0,   0,   0, 
      0,   0,  54,   0,  32,   5, 
     66,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,  45,   0, 
      8, 137, 194,   0,   0, 128, 
      3,  17,  17,   0,  18,   0, 
     16,   0,   1,   0,   0,   0, 
     70,  10,  16,   0,   0,   0, 
      0,   0,  70, 126,  16,   0, 
      0,   0,   0,   0,  45,   0, 
     16, 137, 194,   0,   0, 128, 
      3,  17,  17,   0,  34,   0, 
     16,   0,   1,   0,   0,   0, 
     70,  10,  16,   0,   0,   0, 
      0,   0,  22, 126,  16,   0, 
      1,   0,   0,   0,  31,   0, 
      0,   3,  26,   0,  16,   0, 
      1,   0,   0,   0,  54,   0, 
      8,   5,  18,  32,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   1,   0,   0,   0, 
     62,   0,   0,   1,  21,   0, 
      0,   1,  61,   0,  48, 137, 
    194,   0,   0, 128,   3,  17, 
     17,   0,  98,   0,  16,   0, 
      1,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,   0, 
     38, 125,  16,   0,   0,   0, 
      0,   0,  27,   0,  48,   5, 
     98,   0,  16,   0,   1,   0, 
      0,   0,  86,   6,  16,   0, 
      1,   0,   0,   0,  34,   0, 
     24,  10,  50,   0,  16,   0, 
      2,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     70,   0,  16,   0,   0,   0, 
      0,   0,  30,   0, 120,  10, 
    242,   0,  16,   0,   3,   0, 
      0,   0,   6,   5,  16,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0, 255, 255, 255, 255, 
      1,   0,   0,   0, 255, 255, 
    255, 255,   1,   0,   0,   0, 
     34,   0,  48,   7,  98,   0, 
     16,   0,   1,   0,   0,   0, 
     86,   7,  16,   0,   3,   0, 
      0,   0,  86,   6,  16,   0, 
      1,   0,   0,   0,   1,   0, 
     40,   7,  82,   0,  16,   0, 
      2,   0,   0,   0,   6,   1, 
     16,   0,   2,   0,   0,   0, 
      6,   2,  16,   0,   3,   0, 
      0,   0,  30,   0,  24,   8, 
     50,   0,  16,   0,   3,   0, 
      0,   0,  70,   0,  16,   0, 
      0,   0,   0,   0, 150,   5, 
     16, 128,  65,   0,   0,   0, 
      1,   0,   0,   0,  54,   0, 
     64,   5, 130,   0,  16,   0, 
      0,   0,   0,   0,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     45,   0,  64, 137, 194,   0, 
      0, 128,   3,  17,  17,   0, 
    130,   0,  16,   0,   0,   0, 
      0,   0, 198,  10,  16,   0, 
      0,   0,   0,   0, 150, 115, 
     16,   0,   0,   0,   0,   0, 
     54,   0,  96,   5, 194,   0, 
     16,   0,   3,   0,   0,   0, 
      6,   8,  16,   0,   0,   0, 
      0,   0,  45,   0,   8, 137, 
    194,   0,   0, 128,   3,  17, 
     17,   0,  18,   0,  16,   0, 
      0,   0,   0,   0, 102,  15, 
     16,   0,   3,   0,   0,   0, 
     70, 126,  16,   0,   0,   0, 
      0,   0,  54,   0,  80,   5, 
    162,   0,  16,   0,   2,   0, 
      0,   0,  86,   9,  16,   0, 
      0,   0,   0,   0,  45,   0, 
     16, 137, 194,   0,   0, 128, 
      3,  17,  17,   0,  34,   0, 
     16,   0,   0,   0,   0,   0, 
     70,  15,  16,   0,   2,   0, 
      0,   0,  22, 126,  16,   0, 
      0,   0,   0,   0,  54,   0, 
    104,   5, 210,   0,  16,   0, 
      2,   0,   0,   0,   6,  15, 
     16,   0,   3,   0,   0,   0, 
     45,   0,  32, 137, 194,   0, 
      0, 128,   3,  17,  17,   0, 
     66,   0,  16,   0,   0,   0, 
      0,   0,  70,  14,  16,   0, 
      2,   0,   0,   0, 150, 124, 
     16,   0,   0,   0,   0,   0, 
    138,   0,  48,  15,  98,   0, 
     16,   0,   1,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0,   0,   8,   0,   0,   0, 
      8,   0,   0,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,  16,   0, 
      0,   0,   8,   0,   0,   0, 
      0,   0,   0,   0,   6,   0, 
     16,   0,   1,   0,   0,   0, 
      1,   0,  64,   7, 130,   0, 
     16,   0,   1,   0,   0,   0, 
     10,   0,  16,   0,   1,   0, 
      0,   0,   1,  64,   0,   0, 
    255,   0,   0,   0,  86,   0, 
    112,   5, 226,   0,  16,   0, 
      1,   0,   0,   0,  86,  14, 
     16,   0,   1,   0,   0,   0, 
     56,   0,  24,  10,  50,   0, 
     16,   0,   2,   0,   0,   0, 
    150,   5,  16,   0,   1,   0, 
      0,   0,   2,  64,   0,   0, 
    135,  22, 153,  62, 162,  69, 
     22,  63,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      8,   7,  18,   0,  16,   0, 
      2,   0,   0,   0,  26,   0, 
     16,   0,   2,   0,   0,   0, 
     10,   0,  16,   0,   2,   0, 
      0,   0,  56,   0,  16,   7, 
     34,   0,  16,   0,   2,   0, 
      0,   0,  58,   0,  16,   0, 
      1,   0,   0,   0,   1,  64, 
      0,   0, 213, 120, 233,  61, 
      0,   0,   8,   7,  18,   0, 
     16,   0,   2,   0,   0,   0, 
     26,   0,  16,   0,   2,   0, 
      0,   0,  10,   0,  16,   0, 
      2,   0,   0,   0, 138,   0, 
     48,  15,  98,   0,  16,   0, 
      2,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      8,   0,   0,   0,   8,   0, 
      0,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0,   0,  16,   0,   0,   0, 
      8,   0,   0,   0,   0,   0, 
      0,   0, 246,  15,  16,   0, 
      0,   0,   0,   0,   1,   0, 
     64,   7, 130,   0,  16,   0, 
      2,   0,   0,   0,  58,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0, 255,   0, 
      0,   0,  86,   0, 112,   5, 
    226,   0,  16,   0,   2,   0, 
      0,   0,  86,  14,  16,   0, 
      2,   0,   0,   0,  56,   0, 
     48,  10,  98,   0,  16,   0, 
      2,   0,   0,   0,  86,   6, 
     16,   0,   2,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0,   0, 135,  22, 153,  62, 
    162,  69,  22,  63,   0,   0, 
      0,   0,   0,   0,  16,   7, 
     34,   0,  16,   0,   2,   0, 
      0,   0,  42,   0,  16,   0, 
      2,   0,   0,   0,  26,   0, 
     16,   0,   2,   0,   0,   0, 
     56,   0,  32,   7,  66,   0, 
     16,   0,   2,   0,   0,   0, 
     58,   0,  16,   0,   2,   0, 
      0,   0,   1,  64,   0,   0, 
    213, 120, 233,  61,   0,   0, 
     16,   7,  34,   0,  16,   0, 
      2,   0,   0,   0,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     26,   0,  16,   0,   2,   0, 
      0,   0, 138,   0,  96,  15, 
    194,   0,  16,   0,   2,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   8,   0,   0,   0, 
      8,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  16,   0, 
      0,   0,   8,   0,   0,   0, 
      6,   0,  16,   0,   0,   0, 
      0,   0,  86,   0,  96,   5, 
    194,   0,  16,   0,   2,   0, 
      0,   0, 166,  14,  16,   0, 
      2,   0,   0,   0,   1,   0, 
     40,  10,  82,   0,  16,   0, 
      3,   0,   0,   0,   6,   2, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0, 255,   0, 
      0,   0,   0,   0,   0,   0, 
    255,   0,   0,   0,   0,   0, 
      0,   0,  86,   0,   8,   5, 
     18,   0,  16,   0,   3,   0, 
      0,   0,  10,   0,  16,   0, 
      3,   0,   0,   0,  56,   0, 
     96,  10, 194,   0,  16,   0, 
      2,   0,   0,   0, 166,  14, 
     16,   0,   2,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
    135,  22, 153,  62, 162,  69, 
     22,  63,   0,   0,  32,   7, 
     66,   0,  16,   0,   2,   0, 
      0,   0,  58,   0,  16,   0, 
      2,   0,   0,   0,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     56,   0,  64,   7, 130,   0, 
     16,   0,   2,   0,   0,   0, 
     10,   0,  16,   0,   3,   0, 
      0,   0,   1,  64,   0,   0, 
    213, 120, 233,  61,   0,   0, 
     32,   7,  66,   0,  16,   0, 
      2,   0,   0,   0,  58,   0, 
     16,   0,   2,   0,   0,   0, 
     42,   0,  16,   0,   2,   0, 
      0,   0, 138,   0,  24,  15, 
     50,   0,  16,   0,   3,   0, 
      0,   0,   2,  64,   0,   0, 
      8,   0,   0,   0,   8,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0,  16,   0,   0,   0, 
      8,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     86,   5,  16,   0,   0,   0, 
      0,   0,  86,   0,  24,   5, 
     50,   0,  16,   0,   3,   0, 
      0,   0,  70,   0,  16,   0, 
      3,   0,   0,   0,   1,   0, 
     64,   7, 130,   0,  16,   0, 
      2,   0,   0,   0,  26,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0, 255,   0, 
      0,   0,  86,   0,  64,   5, 
    130,   0,  16,   0,   2,   0, 
      0,   0,  58,   0,  16,   0, 
      2,   0,   0,   0,  56,   0, 
     24,  10,  50,   0,  16,   0, 
      3,   0,   0,   0,  70,   0, 
     16,   0,   3,   0,   0,   0, 
      2,  64,   0,   0, 135,  22, 
    153,  62, 162,  69,  22,  63, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   8,   7, 
     18,   0,  16,   0,   3,   0, 
      0,   0,  26,   0,  16,   0, 
      3,   0,   0,   0,  10,   0, 
     16,   0,   3,   0,   0,   0, 
     56,   0,  64,   7, 130,   0, 
     16,   0,   2,   0,   0,   0, 
     58,   0,  16,   0,   2,   0, 
      0,   0,   1,  64,   0,   0, 
    213, 120, 233,  61,   0,   0, 
     64,   7, 130,   0,  16,   0, 
      2,   0,   0,   0,  58,   0, 
     16,   0,   2,   0,   0,   0, 
     10,   0,  16,   0,   3,   0, 
      0,   0, 138,   0,  24,  15, 
     50,   0,  16,   0,   3,   0, 
      0,   0,   2,  64,   0,   0, 
      8,   0,   0,   0,   8,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0,  16,   0,   0,   0, 
      8,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
    166,  10,  16,   0,   0,   0, 
      0,   0,  86,   0,  56,   5, 
    114,   0,  16,   0,   3,   0, 
      0,   0,  70,   2,  16,   0, 
      3,   0,   0,   0,  56,   0, 
     24,  10,  50,   0,  16,   0, 
      3,   0,   0,   0,  70,   0, 
     16,   0,   3,   0,   0,   0, 
      2,  64,   0,   0, 135,  22, 
    153,  62, 162,  69,  22,  63, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   8,   7, 
     18,   0,  16,   0,   3,   0, 
      0,   0,  26,   0,  16,   0, 
      3,   0,   0,   0,  10,   0, 
     16,   0,   3,   0,   0,   0, 
     56,   0,  16,   7,  34,   0, 
     16,   0,   3,   0,   0,   0, 
     42,   0,  16,   0,   3,   0, 
      0,   0,   1,  64,   0,   0, 
    213, 120, 233,  61,   0,   0, 
      8,   7,  18,   0,  16,   0, 
      3,   0,   0,   0,  26,   0, 
     16,   0,   3,   0,   0,   0, 
     10,   0,  16,   0,   3,   0, 
      0,   0,  51,   0,  16,   7, 
     34,   0,  16,   0,   3,   0, 
      0,   0,  26,   0,  16,   0, 
      2,   0,   0,   0,  10,   0, 
     16,   0,   2,   0,   0,   0, 
     51,   0,  16,   7,  34,   0, 
     16,   0,   3,   0,   0,   0, 
     42,   0,  16,   0,   2,   0, 
      0,   0,  26,   0,  16,   0, 
      3,   0,   0,   0,  51,   0, 
     16,   7,  34,   0,  16,   0, 
      3,   0,   0,   0,  58,   0, 
     16,   0,   2,   0,   0,   0, 
     26,   0,  16,   0,   3,   0, 
      0,   0,  51,   0,  16,   7, 
     34,   0,  16,   0,   3,   0, 
      0,   0,  10,   0,  16,   0, 
      3,   0,   0,   0,  26,   0, 
     16,   0,   3,   0,   0,   0, 
     52,   0,  32,   7,  66,   0, 
     16,   0,   3,   0,   0,   0, 
     26,   0,  16,   0,   2,   0, 
      0,   0,  10,   0,  16,   0, 
      2,   0,   0,   0,  52,   0, 
     32,   7,  66,   0,  16,   0, 
      3,   0,   0,   0,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     42,   0,  16,   0,   3,   0, 
      0,   0,  52,   0,  32,   7, 
     66,   0,  16,   0,   3,   0, 
      0,   0,  58,   0,  16,   0, 
      2,   0,   0,   0,  42,   0, 
     16,   0,   3,   0,   0,   0, 
     52,   0,  32,   7,  66,   0, 
     16,   0,   3,   0,   0,   0, 
     10,   0,  16,   0,   3,   0, 
      0,   0,  42,   0,  16,   0, 
      3,   0,   0,   0,   0,   0, 
     16,   8,  34,   0,  16,   0, 
      3,   0,   0,   0,  26,   0, 
     16, 128,  65,   0,   0,   0, 
      3,   0,   0,   0,  42,   0, 
     16,   0,   3,   0,   0,   0, 
     56,   0,  32,   7,  66,   0, 
     16,   0,   3,   0,   0,   0, 
     42,   0,  16,   0,   3,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,  62,  49,   0, 
     64,   7, 130,   0,  16,   0, 
      3,   0,   0,   0,  26,   0, 
     16,   0,   3,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
      0,  65,  49,   0,  32,   7, 
     66,   0,  16,   0,   3,   0, 
      0,   0,  26,   0,  16,   0, 
      3,   0,   0,   0,  42,   0, 
     16,   0,   3,   0,   0,   0, 
     60,   0,  32,   7,  66,   0, 
     16,   0,   3,   0,   0,   0, 
     42,   0,  16,   0,   3,   0, 
      0,   0,  58,   0,  16,   0, 
      3,   0,   0,   0,  31,   0, 
      4,   3,  42,   0,  16,   0, 
      3,   0,   0,   0,  54,   0, 
      8,   5,  18,  32,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   1,   0,   0,   0, 
     62,   0,   0,   1,  21,   0, 
      0,   1,   0,   0,  16,   7, 
     34,   0,  16,   0,   2,   0, 
      0,   0,  42,   0,  16,   0, 
      2,   0,   0,   0,  26,   0, 
     16,   0,   2,   0,   0,   0, 
      0,   0,  32,   7,  66,   0, 
     16,   0,   2,   0,   0,   0, 
     58,   0,  16,   0,   2,   0, 
      0,   0,  26,   0,  16,   0, 
      2,   0,   0,   0,   0,   0, 
     32,   7,  66,   0,  16,   0, 
      2,   0,   0,   0,  10,   0, 
     16,   0,   3,   0,   0,   0, 
     42,   0,  16,   0,   2,   0, 
      0,   0,  56,   0,  32,   7, 
     66,   0,  16,   0,   2,   0, 
      0,   0,  42,   0,  16,   0, 
      2,   0,   0,   0,   1,  64, 
      0,   0,   0,   0, 128,  62, 
      0,   0,  32,   8,  66,   0, 
     16,   0,   2,   0,   0,   0, 
     10,   0,  16, 128,  65,   0, 
      0,   0,   2,   0,   0,   0, 
     42,   0,  16,   0,   2,   0, 
      0,   0,  57,   0,  32,   8, 
     66,   0,  16,   0,   3,   0, 
      0,   0,  42,   0,  16, 128, 
    129,   0,   0,   0,   2,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,  31,   0, 
      4,   3,  42,   0,  16,   0, 
      3,   0,   0,   0,  14,   0, 
      8,   8,  18,   0,  16,   0, 
      4,   0,   0,   0,  42,   0, 
     16, 128, 129,   0,   0,   0, 
      2,   0,   0,   0,  26,   0, 
     16,   0,   3,   0,   0,   0, 
     30,   0, 120,  10, 242,   0, 
     16,   0,   5,   0,   0,   0, 
      6,   0,  16,   0,   4,   0, 
      0,   0,   2,  64,   0,   0, 
    255, 255, 255, 255, 253, 255, 
    255, 255,   1,   0,   0,   0, 
    254, 255, 255, 255,  56,   0, 
    120,   7, 242,   0,  16,   0, 
      6,   0,   0,   0,  86,   5, 
     16,   0,   3,   0,   0,   0, 
    214,   8,  16,   0,   5,   0, 
      0,   0,  56,   0, 120,  10, 
    242,   0,  16,   0,   7,   0, 
      0,   0, 214,   8,  16,   0, 
      5,   0,   0,   0,   2,  64, 
      0,   0,   0,   8, 128,  69, 
      0,   8, 128,  69,   0,   8, 
    128,  69,   0,   8, 128,  69, 
      0,   0, 120,   8, 242,   0, 
     16,   0,   8,   0,   0,   0, 
    214,   8,  16, 128,  65,   0, 
      0,   0,   5,   0,   0,   0, 
     70,  14,  16,   0,   7,   0, 
      0,   0,   0,   0, 120,   8, 
    242,   0,  16,   0,   7,   0, 
      0,   0,  70,  14,  16,   0, 
      7,   0,   0,   0,  70,  14, 
     16, 128,  65,   0,   0,   0, 
      8,   0,   0,   0,   0,   0, 
    120,   8, 242,   0,  16,   0, 
      8,   0,   0,   0, 214,   8, 
     16,   0,   5,   0,   0,   0, 
     70,  14,  16, 128,  65,   0, 
      0,   0,   7,   0,   0,   0, 
     56,   0,  32,   7,  66,   0, 
     16,   0,   3,   0,   0,   0, 
     26,   0,  16,   0,   3,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   8, 128,  69,   0,   0, 
     64,   8, 130,   0,  16,   0, 
      3,   0,   0,   0,  26,   0, 
     16, 128,  65,   0,   0,   0, 
      3,   0,   0,   0,  42,   0, 
     16,   0,   3,   0,   0,   0, 
      0,   0,  32,   8,  66,   0, 
     16,   0,   3,   0,   0,   0, 
     58,   0,  16, 128,  65,   0, 
      0,   0,   3,   0,   0,   0, 
     42,   0,  16,   0,   3,   0, 
      0,   0,   0,   0,  64,   8, 
    130,   0,  16,   0,   3,   0, 
      0,   0,  42,   0,  16, 128, 
     65,   0,   0,   0,   3,   0, 
      0,   0,  26,   0,  16,   0, 
      3,   0,   0,   0,  56,   0, 
    120,   7, 242,   0,  16,   0, 
      9,   0,   0,   0, 166,  10, 
     16,   0,   3,   0,   0,   0, 
     70,  14,  16,   0,   7,   0, 
      0,   0,   0,   0, 120,   8, 
    242,   0,  16,   0,   9,   0, 
      0,   0,  70,  14,  16, 128, 
     65,   0,   0,   0,   6,   0, 
      0,   0,  70,  14,  16,   0, 
      9,   0,   0,   0,  56,   0, 
    120,   7, 242,   0,  16,   0, 
      7,   0,   0,   0, 246,  15, 
     16,   0,   3,   0,   0,   0, 
     70,  14,  16,   0,   7,   0, 
      0,   0,   0,   0, 120,   7, 
    242,   0,  16,   0,   7,   0, 
      0,   0,  70,  14,  16,   0, 
      7,   0,   0,   0,  70,  14, 
     16,   0,   9,   0,   0,   0, 
     56,   0, 120,   7, 242,   0, 
     16,   0,   9,   0,   0,   0, 
    166,  10,  16,   0,   3,   0, 
      0,   0,  70,  14,  16,   0, 
      8,   0,   0,   0,   0,   0, 
    120,   7, 242,   0,  16,   0, 
      7,   0,   0,   0,  70,  14, 
     16,   0,   7,   0,   0,   0, 
     70,  14,  16,   0,   9,   0, 
      0,   0,  56,   0, 120,   7, 
    242,   0,  16,   0,   8,   0, 
      0,   0, 246,  15,  16,   0, 
      3,   0,   0,   0,  70,  14, 
     16,   0,   8,   0,   0,   0, 
      0,   0, 120,   7, 242,   0, 
     16,   0,   7,   0,   0,   0, 
     70,  14,  16,   0,   7,   0, 
      0,   0,  70,  14,  16,   0, 
      8,   0,   0,   0,   0,   0, 
    120,   9, 242,   0,  16,   0, 
      6,   0,   0,   0, 166,  10, 
     16, 128, 129,   0,   0,   0, 
      2,   0,   0,   0,  70,  14, 
     16, 128,  65,   0,   0,   0, 
      6,   0,   0,   0,   0,   0, 
    120,   8, 242,   0,  16,   0, 
      6,   0,   0,   0,  70,  14, 
     16, 128,  65,   0,   0,   0, 
      7,   0,   0,   0,  70,  14, 
     16,   0,   6,   0,   0,   0, 
     49,   0,  64,   8, 130,   0, 
     16,   0,   4,   0,   0,   0, 
     10,   0,  16, 128, 129,   0, 
      0,   0,   6,   0,   0,   0, 
      1,  64,   0,   0, 202, 242, 
     73, 113,  54,   0,  40,   5, 
     82,   0,  16,   0,   7,   0, 
      0,   0,  86,   7,  16,   0, 
      5,   0,   0,   0,  54,   0, 
     80,   6, 162,   0,  16,   0, 
      7,   0,   0,   0,   6,   4, 
     16, 128, 129,   0,   0,   0, 
      6,   0,   0,   0,  54,   0, 
     16,   5,  34,   0,  16,   0, 
      4,   0,   0,   0,   1,  64, 
      0,   0, 202, 242,  73, 113, 
     55,   0,  80,   9, 162,   0, 
     16,   0,   4,   0,   0,   0, 
    246,  15,  16,   0,   4,   0, 
      0,   0,   6,   4,  16,   0, 
      7,   0,   0,   0,   6,   4, 
     16,   0,   4,   0,   0,   0, 
     49,   0,   8,   8,  18,   0, 
     16,   0,   6,   0,   0,   0, 
     26,   0,  16, 128, 129,   0, 
      0,   0,   6,   0,   0,   0, 
     58,   0,  16,   0,   4,   0, 
      0,   0,  55,   0,  80,   9, 
    162,   0,  16,   0,   4,   0, 
      0,   0,   6,   0,  16,   0, 
      6,   0,   0,   0, 166,  14, 
     16,   0,   7,   0,   0,   0, 
     86,  13,  16,   0,   4,   0, 
      0,   0,  49,   0,   8,   8, 
     18,   0,  16,   0,   6,   0, 
      0,   0,  42,   0,  16, 128, 
    129,   0,   0,   0,   6,   0, 
      0,   0,  58,   0,  16,   0, 
      4,   0,   0,   0,  54,   0, 
     80,   6, 162,   0,  16,   0, 
      5,   0,   0,   0, 166,  14, 
     16, 128, 129,   0,   0,   0, 
      6,   0,   0,   0,  55,   0, 
     80,   9, 162,   0,  16,   0, 
      4,   0,   0,   0,   6,   0, 
     16,   0,   6,   0,   0,   0, 
      6,   4,  16,   0,   5,   0, 
      0,   0,  86,  13,  16,   0, 
      4,   0,   0,   0,  56,   0, 
      8,   7,  18,   0,  16,   0, 
      5,   0,   0,   0,  26,   0, 
     16,   0,   3,   0,   0,   0, 
     10,   0,  16,   0,   4,   0, 
      0,   0,  56,   0,  16,   7, 
     34,   0,  16,   0,   5,   0, 
      0,   0,  10,   0,  16,   0, 
      4,   0,   0,   0,   1,  64, 
      0,   0,   0,   8, 128,  69, 
      0,   0,   8,   8,  18,   0, 
     16,   0,   6,   0,   0,   0, 
     10,   0,  16, 128,  65,   0, 
      0,   0,   4,   0,   0,   0, 
     26,   0,  16,   0,   5,   0, 
      0,   0,   0,   0,  16,   8, 
     34,   0,  16,   0,   5,   0, 
      0,   0,  26,   0,  16,   0, 
      5,   0,   0,   0,  10,   0, 
     16, 128,  65,   0,   0,   0, 
      6,   0,   0,   0,   0,   0, 
      8,   8,  18,   0,  16,   0, 
      6,   0,   0,   0,  10,   0, 
     16,   0,   4,   0,   0,   0, 
     26,   0,  16, 128,  65,   0, 
      0,   0,   5,   0,   0,   0, 
     56,   0,  16,   7,  34,   0, 
     16,   0,   6,   0,   0,   0, 
     42,   0,  16,   0,   3,   0, 
      0,   0,  26,   0,  16,   0, 
      5,   0,   0,   0,   0,   0, 
     16,   8,  34,   0,  16,   0, 
      6,   0,   0,   0,  10,   0, 
     16, 128,  65,   0,   0,   0, 
      5,   0,   0,   0,  26,   0, 
     16,   0,   6,   0,   0,   0, 
     56,   0,  16,   7,  34,   0, 
     16,   0,   5,   0,   0,   0, 
     58,   0,  16,   0,   3,   0, 
      0,   0,  26,   0,  16,   0, 
      5,   0,   0,   0,   0,   0, 
     16,   7,  34,   0,  16,   0, 
      5,   0,   0,   0,  26,   0, 
     16,   0,   5,   0,   0,   0, 
     26,   0,  16,   0,   6,   0, 
      0,   0,  56,   0,  16,   7, 
     34,   0,  16,   0,   6,   0, 
      0,   0,  42,   0,  16,   0, 
      3,   0,   0,   0,  10,   0, 
     16,   0,   6,   0,   0,   0, 
      0,   0,  16,   7,  34,   0, 
     16,   0,   5,   0,   0,   0, 
     26,   0,  16,   0,   5,   0, 
      0,   0,  26,   0,  16,   0, 
      6,   0,   0,   0,  56,   0, 
      8,   7,  18,   0,  16,   0, 
      6,   0,   0,   0,  58,   0, 
     16,   0,   3,   0,   0,   0, 
     10,   0,  16,   0,   6,   0, 
      0,   0,   0,   0,  16,   7, 
     34,   0,  16,   0,   5,   0, 
      0,   0,  26,   0,  16,   0, 
      5,   0,   0,   0,  10,   0, 
     16,   0,   6,   0,   0,   0, 
      0,   0,   8,   9,  18,   0, 
     16,   0,   5,   0,   0,   0, 
     42,   0,  16, 128, 129,   0, 
      0,   0,   2,   0,   0,   0, 
     10,   0,  16, 128,  65,   0, 
      0,   0,   5,   0,   0,   0, 
      0,   0,   8,   8,  18,   0, 
     16,   0,   5,   0,   0,   0, 
     26,   0,  16, 128,  65,   0, 
      0,   0,   5,   0,   0,   0, 
     10,   0,  16,   0,   5,   0, 
      0,   0,  54,   0,  32,   6, 
     66,   0,  16,   0,   4,   0, 
      0,   0,  10,   0,  16, 128, 
    129,   0,   0,   0,   5,   0, 
      0,   0,  49,   0,   8,   7, 
     18,   0,  16,   0,   5,   0, 
      0,   0,  42,   0,  16,   0, 
      4,   0,   0,   0,  58,   0, 
     16,   0,   4,   0,   0,   0, 
     55,   0,  48,   9,  98,   0, 
     16,   0,   4,   0,   0,   0, 
      6,   0,  16,   0,   5,   0, 
      0,   0,   6,   2,  16,   0, 
      4,   0,   0,   0,  86,   7, 
     16,   0,   4,   0,   0,   0, 
     49,   0,  64,   8, 130,   0, 
     16,   0,   4,   0,   0,   0, 
     58,   0,  16, 128, 129,   0, 
      0,   0,   6,   0,   0,   0, 
     42,   0,  16,   0,   4,   0, 
      0,   0,  55,   0,  48,   9, 
     98,   0,  16,   0,   4,   0, 
      0,   0, 246,  15,  16,   0, 
      4,   0,   0,   0, 166,  11, 
     16,   0,   5,   0,   0,   0, 
     86,   6,  16,   0,   4,   0, 
      0,   0,  30,   0,  24,  10, 
     50,   0,  16,   0,   5,   0, 
      0,   0,   6,   0,  16,   0, 
      4,   0,   0,   0,   2,  64, 
      0,   0,   2,   0,   0,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     56,   0,  72,   7, 146,   0, 
     16,   0,   4,   0,   0,   0, 
     86,   5,  16,   0,   3,   0, 
      0,   0,   6,   4,  16,   0, 
      5,   0,   0,   0,  56,   0, 
     24,  10,  50,   0,  16,   0, 
      6,   0,   0,   0,  70,   0, 
     16,   0,   5,   0,   0,   0, 
      2,  64,   0,   0,   0,   8, 
    128,  69,   0,   8, 128,  69, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  96,   8, 
    194,   0,  16,   0,   6,   0, 
      0,   0,   6,   4,  16, 128, 
     65,   0,   0,   0,   5,   0, 
      0,   0,   6,   4,  16,   0, 
      6,   0,   0,   0,   0,   0, 
     24,   8,  50,   0,  16,   0, 
      6,   0,   0,   0, 230,  10, 
     16, 128,  65,   0,   0,   0, 
      6,   0,   0,   0,  70,   0, 
     16,   0,   6,   0,   0,   0, 
      0,   0,  96,   8, 194,   0, 
     16,   0,   6,   0,   0,   0, 
      6,   4,  16,   0,   5,   0, 
      0,   0,   6,   4,  16, 128, 
     65,   0,   0,   0,   6,   0, 
      0,   0,  56,   0,  24,   7, 
     50,   0,  16,   0,   7,   0, 
      0,   0, 166,  10,  16,   0, 
      3,   0,   0,   0,  70,   0, 
     16,   0,   6,   0,   0,   0, 
      0,   0,  24,   8,  50,   0, 
     16,   0,   7,   0,   0,   0, 
    198,   0,  16, 128,  65,   0, 
      0,   0,   4,   0,   0,   0, 
     70,   0,  16,   0,   7,   0, 
      0,   0,  56,   0,  24,   7, 
     50,   0,  16,   0,   6,   0, 
      0,   0, 246,  15,  16,   0, 
      3,   0,   0,   0,  70,   0, 
     16,   0,   6,   0,   0,   0, 
      0,   0,  24,   7,  50,   0, 
     16,   0,   6,   0,   0,   0, 
     70,   0,  16,   0,   6,   0, 
      0,   0,  70,   0,  16,   0, 
      7,   0,   0,   0,  56,   0, 
     48,   7,  98,   0,  16,   0, 
      3,   0,   0,   0, 166,  10, 
     16,   0,   3,   0,   0,   0, 
    166,  11,  16,   0,   6,   0, 
      0,   0,   0,   0,  48,   7, 
     98,   0,  16,   0,   3,   0, 
      0,   0,  86,   6,  16,   0, 
      3,   0,   0,   0,   6,   1, 
     16,   0,   6,   0,   0,   0, 
     56,   0,  24,   7,  50,   0, 
     16,   0,   6,   0,   0,   0, 
    246,  15,  16,   0,   3,   0, 
      0,   0, 230,  10,  16,   0, 
      6,   0,   0,   0,   0,   0, 
     48,   7,  98,   0,  16,   0, 
      3,   0,   0,   0,  86,   6, 
     16,   0,   3,   0,   0,   0, 
      6,   1,  16,   0,   6,   0, 
      0,   0,   0,   0,  72,   9, 
    146,   0,  16,   0,   4,   0, 
      0,   0, 166,  10,  16, 128, 
    129,   0,   0,   0,   2,   0, 
      0,   0,   6,  12,  16, 128, 
     65,   0,   0,   0,   4,   0, 
      0,   0,   0,   0,  48,   8, 
     98,   0,  16,   0,   3,   0, 
      0,   0,  86,   6,  16, 128, 
     65,   0,   0,   0,   3,   0, 
      0,   0,   6,   3,  16,   0, 
      4,   0,   0,   0,  54,   0, 
     96,   6, 194,   0,  16,   0, 
      5,   0,   0,   0,  86,   9, 
     16, 128, 129,   0,   0,   0, 
      3,   0,   0,   0,  49,   0, 
     32,   7,  66,   0,  16,   0, 
      2,   0,   0,   0,  42,   0, 
     16,   0,   5,   0,   0,   0, 
     42,   0,  16,   0,   4,   0, 
      0,   0,  55,   0,  48,   9, 
     98,   0,  16,   0,   3,   0, 
      0,   0, 166,  10,  16,   0, 
      2,   0,   0,   0,   6,   2, 
     16,   0,   5,   0,   0,   0, 
     86,   6,  16,   0,   4,   0, 
      0,   0,  49,   0,  32,   7, 
     66,   0,  16,   0,   2,   0, 
      0,   0,  58,   0,  16,   0, 
      5,   0,   0,   0,  42,   0, 
     16,   0,   3,   0,   0,   0, 
     55,   0,  32,   9,  66,   0, 
     16,   0,   2,   0,   0,   0, 
     42,   0,  16,   0,   2,   0, 
      0,   0,  26,   0,  16,   0, 
      5,   0,   0,   0,  26,   0, 
     16,   0,   3,   0,   0,   0, 
     18,   0,   0,   1,  54,   0, 
     32,   5,  66,   0,  16,   0, 
      2,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,   0, 
     21,   0,   0,   1,  56,   0, 
     32,   7,  66,   0,  16,   0, 
      2,   0,   0,   0,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     42,   0,  16,   0,   2,   0, 
      0,   0,  49,   0,  16,   7, 
     34,   0,  16,   0,   3,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,  63,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     55,   0,  32,   9,  66,   0, 
     16,   0,   2,   0,   0,   0, 
     26,   0,  16,   0,   3,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,  63,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     29,   0,  16,   7,  34,   0, 
     16,   0,   3,   0,   0,   0, 
      1,  64,   0,   0, 111,  18, 
      3,  59,  42,   0,  16,   0, 
      2,   0,   0,   0,  31,   0, 
      4,   3,  26,   0,  16,   0, 
      3,   0,   0,   0,  54,   0, 
      8,   5,  18,  32,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   1,   0,   0,   0, 
     62,   0,   0,   1,  21,   0, 
      0,   1,   0,   0,   8,   7, 
     18,   0,  16,   0,   1,   0, 
      0,   0,  58,   0,  16,   0, 
      2,   0,   0,   0,  10,   0, 
     16,   0,   3,   0,   0,   0, 
     56,   0,   8,   7,  18,   0, 
     16,   0,   2,   0,   0,   0, 
     10,   0,  16,   0,   2,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,  64,   0,   0, 
      8,   8,  18,   0,  16,   0, 
      1,   0,   0,   0,  10,   0, 
     16,   0,   1,   0,   0,   0, 
     10,   0,  16, 128,  65,   0, 
      0,   0,   2,   0,   0,   0, 
      0,   0,   8,   8,  18,   0, 
     16,   0,   2,   0,   0,   0, 
     10,   0,  16, 128,  65,   0, 
      0,   0,   2,   0,   0,   0, 
     26,   0,  16,   0,   2,   0, 
      0,   0,  29,   0,   8,   9, 
     18,   0,  16,   0,   1,   0, 
      0,   0,  10,   0,  16, 128, 
    129,   0,   0,   0,   1,   0, 
      0,   0,  10,   0,  16, 128, 
    129,   0,   0,   0,   2,   0, 
      0,   0,  55,   0,  24,   9, 
     50,   0,  16,   0,   0,   0, 
      0,   0,   6,   0,  16,   0, 
      1,   0,   0,   0, 102,  10, 
     16,   0,   0,   0,   0,   0, 
    198,   0,  16,   0,   0,   0, 
      0,   0, 138,   0,  96,  15, 
    194,   0,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   8,   0,   0,   0, 
      8,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  16,   0, 
      0,   0,   8,   0,   0,   0, 
     86,   5,  16,   0,   0,   0, 
      0,   0, 138,   0,  24,  15, 
     50,   0,  16,   0,   2,   0, 
      0,   0,   2,  64,   0,   0, 
      8,   0,   0,   0,   8,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0,  16,   0,   0,   0, 
      8,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      6,   0,  16,   0,   0,   0, 
      0,   0,  86,   0,  96,   5, 
    194,   0,  16,   0,   0,   0, 
      0,   0, 166,  14,  16,   0, 
      0,   0,   0,   0,  56,   0, 
     96,  10, 194,   0,  16,   0, 
      0,   0,   0,   0, 166,  14, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,  63,   0,   0, 
      0,  63,  86,   0,  24,   5, 
     50,   0,  16,   0,   2,   0, 
      0,   0,  70,   0,  16,   0, 
      2,   0,   0,   0,  56,   0, 
     24,  10,  50,   0,  16,   0, 
      2,   0,   0,   0,  70,   0, 
     16,   0,   2,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0,  63,   0,   0,   0,  63, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  96,   7, 
    194,   0,  16,   0,   0,   0, 
      0,   0, 166,  14,  16,   0, 
      0,   0,   0,   0,   6,   4, 
     16,   0,   2,   0,   0,   0, 
      0,   0,  96,  10, 194,   0, 
     16,   0,   0,   0,   0,   0, 
    166,  14,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,  63, 
      0,   0,   0,  63,  27,   0, 
     96,   5, 194,   0,  16,   0, 
      0,   0,   0,   0, 166,  14, 
     16,   0,   0,   0,   0,   0, 
     41,   0,  96,  10, 194,   0, 
     16,   0,   0,   0,   0,   0, 
    166,  14,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,  16,   0,   0,   0, 
      8,   0,   0,   0,  30,   0, 
     32,   7,  66,   0,  16,   0, 
      0,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
      0, 255,  30,   0,  64,   7, 
    130,   0,  16,   0,   0,   0, 
      0,   0,  42,   0,  16,   0, 
      0,   0,   0,   0,  58,   0, 
     16,   0,   0,   0,   0,   0, 
      1,   0,  24,  10,  50,   0, 
     16,   0,   0,   0,   0,   0, 
     70,   0,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
    255,   0,   0,   0, 255,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  86,   0, 
     24,   5,  50,   0,  16,   0, 
      0,   0,   0,   0,  70,   0, 
     16,   0,   0,   0,   0,   0, 
     56,   0,  24,  10,  50,   0, 
     16,   0,   0,   0,   0,   0, 
     70,   0,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,  63,   0,   0, 
      0,  63,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      8,   7,  18,   0,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
     26,   0,  16,   0,   0,   0, 
      0,   0,   0,   0,   8,   7, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,  63, 
     27,   0,   8,   5,  18,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  30,   0,   8,   7, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  58,   0,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
      0,   0,  16,   8,  34,   0, 
     16,   0,   0,   0,   0,   0, 
     42,   0,  16, 128,  65,   0, 
      0,   0,   2,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
    128,  63, 138,   0,  96,  15, 
    194,   0,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   8,   0,   0,   0, 
      8,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  16,   0, 
      0,   0,   8,   0,   0,   0, 
    166,  14,  16,   0,   0,   0, 
      0,   0,  56,   0,  24,   7, 
     50,   0,  16,   0,   1,   0, 
      0,   0,  86,   5,  16,   0, 
      0,   0,   0,   0, 150,   5, 
     16,   0,   1,   0,   0,   0, 
     86,   0,  96,   5, 194,   0, 
     16,   0,   0,   0,   0,   0, 
    166,  14,  16,   0,   0,   0, 
      0,   0,  56,   0,  96,   7, 
    194,   0,  16,   0,   0,   0, 
      0,   0, 166,  10,  16,   0, 
      2,   0,   0,   0, 166,  14, 
     16,   0,   0,   0,   0,   0, 
      0,   0,  96,   7, 194,   0, 
     16,   0,   0,   0,   0,   0, 
    166,  14,  16,   0,   0,   0, 
      0,   0,   6,   4,  16,   0, 
      1,   0,   0,   0,   0,   0, 
     96,  10, 194,   0,  16,   0, 
      0,   0,   0,   0, 166,  14, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,  63,   0,   0, 
      0,  63,  27,   0,   0,   5, 
    194,   0,  16,   0,   0,   0, 
      0,   0, 166,  14,  16,   0, 
      0,   0,   0,   0,  36,   0, 
      0,  10, 194,   0,  16,   0, 
      0,   0,   0,   0, 166,  14, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,  37,   0,   0,  10, 
    194,   0,  16,   0,   0,   0, 
      0,   0, 166,  14,  16,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0, 255,   0, 
      0,   0, 255,   0,   0,   0, 
     41,   0,   0,  10, 194,   0, 
     16,   0,   0,   0,   0,   0, 
    166,  14,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,  16,   0,   0,   0, 
      8,   0,   0,   0,  30,   0, 
      0,   7,  66,   0,  16,   0, 
      0,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
      0, 255,  30,   0,   0,   7, 
     66,   0,  16,   0,   0,   0, 
      0,   0,  42,   0,  16,   0, 
      0,   0,   0,   0,  58,   0, 
     16,   0,   0,   0,   0,   0, 
      1,   0,   8,   7,  18,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
    255,   0,   0,   0,  56,   0, 
     16,   7,  34,   0,  16,   0, 
      0,   0,   0,   0,  26,   0, 
     16,   0,   0,   0,   0,   0, 
     58,   0,  16,   0,   1,   0, 
      0,   0,  86,   0,   8,   5, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,  56,   0, 
      8,   7,  18,   0,  16,   0, 
      0,   0,   0,   0,  42,   0, 
     16,   0,   2,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,   0,   0,   8,   7, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,  26,   0, 
     16,   0,   0,   0,   0,   0, 
      0,   0,   8,   7,  18,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,  63,  27,   0, 
      0,   5,  18,   0,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
     36,   0,   0,   7,  18,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,  37,   0, 
      0,   7,  18,   0,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0, 255,   0, 
      0,   0,  30,   0,   0,   7, 
     18,  32,  16,   0,   0,   0, 
      0,   0,  42,   0,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
     62,   0,   0,   1,  83,  84, 
     65,  84, 148,   0,   0,   0, 
    215,   0,   0,   0,  10,   0, 
      0,   0,   0,   0,   0,   0, 
      2,   0,   0,   0, 119,   0, 
      0,   0,  18,   0,   0,   0, 
      8,   0,   0,   0,   5,   0, 
      0,   0,   4,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      6,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  13,   0, 
      0,   0,   9,   0,   0,   0, 
     18,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0
};

#if 0
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer ToonTable
// {
//
//   float4 toon[32];                   // Offset:    0 Size:   512
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// smp0                              sampler      NA          NA             s0      1 
// smpP                              sampler      NA          NA             s1      1 
// tex0                              texture  float4          2d             t0      1 
// ToonTable                         cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
// COLOR                    0   xyz         2     NONE   float   xyz 
// TEXCOORD                 1   xy          3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
// SV_TARGET                1   x           1   TARGET    uint   x   
//
ps_4_0
dcl_constantbuffer CB0[32], dynamicIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_input_ps linear noperspective v2.xyz
dcl_input_ps constant v3.xy
dcl_output o0.xyzw
dcl_output o1.x
dcl_temps 4
sample r0.xyzw, v1.xyxx, t0.xyzw, s0
sample_l r1.xyzw, v1.xyxx, t0.xyzw, s1, l(0.000000)
mad r1.x, r1.w, l(255.000000), l(0.500000)
round_ni r1.x, r1.x
add r1.y, r1.x, l(-0.500000)
lt r1.y, r1.y, l(0.000000)
discard_nz r1.y
mad r1.y, r0.w, l(255.000000), l(0.500000)
round_ni r1.y, r1.y
lt r1.zw, l(0.000000, 0.000000, 254.500000, 0.500000), r1.xxxy
movc r1.x, r1.w, r1.y, r1.x
movc r1.x, r1.z, l(255.000000), r1.x
max r0.w, r0.w, l(0.000015)
div_sat r0.xyz, r0.xyzx, r0.wwww
mad r0.w, v3.x, r1.x, l(127.000000)
mul r0.w, r0.w, l(0.003922)
add r1.x, v3.y, l(0.500000)
ftou r1.x, r1.x
ushr r1.y, r1.x, l(6)
if_nz r1.y
  mad r1.z, v2.x, l(0.121569), l(0.500000)
  ftoi r1.z, r1.z
  imax r1.z, r1.z, l(0)
  imin r1.z, r1.z, l(31)
  ieq r1.w, r1.y, l(1)
  movc r2.xyz, r1.wwww, cb0[r1.z + 0].xyzx, v2.xxxx
  mov r3.xyz, cb0[r1.z + 0].xyzx
else 
  mov r2.xyz, v2.xyzx
  mov r3.xyz, l(0,0,0,0)
endif 
mad r0.xyz, r2.xyzx, r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
round_ni r0.xyzw, r0.xyzw
ieq r1.y, r1.y, l(2)
add r2.xyz, r3.xyzx, r0.xyzx
movc r0.xyz, r1.yyyy, r2.xyzx, r0.xyzx
max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r0.xyz, r0.xyzx, l(255.000000, 255.000000, 255.000000, 0.000000)
mul o0.xyz, r0.xyzx, l(0.003922, 0.003922, 0.003922, 0.000000)
min r0.x, r0.w, l(31.000000)
mul o0.w, r0.x, l(0.032258)
and r0.x, r1.x, l(63)
iadd o1.x, r0.x, l(128)
ret 
// Approximately 44 instruction slots used
#endif

static const unsigned char kGpuRasterPSF[] =
{
     68,  88,  66,  67, 170,  29, 
     42,  94, 180, 102,  11, 190, 
    107,  36, 164, 203,  80, 104, 
     93, 232,   1,   0,   0,   0, 
     36,   8,   0,   0,   5,   0, 
      0,   0,  52,   0,   0,   0, 
    100,   1,   0,   0, 240,   1, 
      0,   0,  60,   2,   0,   0, 
    168,   7,   0,   0,  82,  68, 
     69,  70,  40,   1,   0,   0, 
      1,   0,   0,   0, 184,   0, 
      0,   0,   4,   0,   0,   0, 
     28,   0,   0,   0,   0,   4, 
    255, 255,   0, 129,   0,   0, 
      0,   1,   0,   0, 156,   0, 
      0,   0,   3,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   1,   0,   0,   0, 
    161,   0,   0,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      1,   0,   0,   0,   1,   0, 
      0,   0, 166,   0,   0,   0, 
      2,   0,   0,   0,   5,   0, 
      0,   0,   4,   0,   0,   0, 
    255, 255, 255, 255,   0,   0, 
      0,   0,   1,   0,   0,   0, 
     13,   0,   0,   0, 171,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   1,   0,   0,   0, 
    115, 109, 112,  48,   0, 115, 
    109, 112,  80,   0, 116, 101, 
    120,  48,   0,  84, 111, 111, 
    110,  84,  97,  98, 108, 101, 
      0, 171, 171, 171, 171,   0, 
      0,   0,   1,   0,   0,   0, 
    208,   0,   0,   0,   0,   2, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0, 232,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   2,   0,   0,   2,   0, 
      0,   0, 240,   0,   0,   0, 
      0,   0,   0,   0, 116, 111, 
    111, 110,   0, 171, 171, 171, 
      1,   0,   3,   0,   1,   0, 
      4,   0,  32,   0,   0,   0, 
      0,   0,   0,   0,  77, 105, 
     99, 114, 111, 115, 111, 102, 
    116,  32,  40,  82,  41,  32, 
     72,  76,  83,  76,  32,  83, 
    104,  97, 100, 101, 114,  32, 
     67, 111, 109, 112, 105, 108, 
    101, 114,  32,  49,  48,  46, 
     49,   0,  73,  83,  71,  78, 
    132,   0,   0,   0,   4,   0, 
      0,   0,   8,   0,   0,   0, 
    104,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0,  15,   0,   0,   0, 
    116,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      3,   0,   0,   0,   1,   0, 
      0,   0,   3,   3,   0,   0, 
    125,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      3,   0,   0,   0,   2,   0, 
      0,   0,   7,   7,   0,   0, 
    116,   0,   0,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
      3,   0,   0,   0,   3,   0, 
      0,   0,   3,   3,   0,   0, 
     83,  86,  95,  80,  79,  83, 
     73,  84,  73,  79,  78,   0, 
     84,  69,  88,  67,  79,  79, 
     82,  68,   0,  67,  79,  76, 
     79,  82,   0, 171,  79,  83, 
     71,  78,  68,   0,   0,   0, 
      2,   0,   0,   0,   8,   0, 
      0,   0,  56,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   3,   0,   0,   0, 
      0,   0,   0,   0,  15,   0, 
      0,   0,  56,   0,   0,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      1,   0,   0,   0,   1,  14, 
      0,   0,  83,  86,  95,  84, 
     65,  82,  71,  69,  84,   0, 
    171, 171,  83,  72,  68,  82, 
    100,   5,   0,   0,  64,   0, 
      0,   0,  89,   1,   0,   0, 
     89,   8,   0,   4,  70, 142, 
     32,   0,   0,   0,   0,   0, 
     32,   0,   0,   0,  90,   0, 
      0,   3,   0,  96,  16,   0, 
      0,   0,   0,   0,  90,   0, 
      0,   3,   0,  96,  16,   0, 
      1,   0,   0,   0,  88,  24, 
      0,   4,   0, 112,  16,   0, 
      0,   0,   0,   0,  85,  85, 
      0,   0,  98,  16,   0,   3, 
     50,  16,  16,   0,   1,   0, 
      0,   0,  98,  32,   0,   3, 
    114,  16,  16,   0,   2,   0, 
      0,   0,  98,   8,   0,   3, 
     50,  16,  16,   0,   3,   0, 
      0,   0, 101,   0,   0,   3, 
    242,  32,  16,   0,   0,   0, 
      0,   0, 101,   0,   0,   3, 
     18,  32,  16,   0,   1,   0, 
      0,   0, 104,   0,   0,   2, 
      4,   0,   0,   0,  69,   0, 
      0,   9, 242,   0,  16,   0, 
      0,   0,   0,   0,  70,  16, 
     16,   0,   1,   0,   0,   0, 
     70, 126,  16,   0,   0,   0, 
      0,   0,   0,  96,  16,   0, 
      0,   0,   0,   0,  72,   0, 
      0,  11, 242,   0,  16,   0, 
      1,   0,   0,   0,  70,  16, 
     16,   0,   1,   0,   0,   0, 
     70, 126,  16,   0,   0,   0, 
      0,   0,   0,  96,  16,   0, 
      1,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,   0, 
     50,   0,   0,   9,  18,   0, 
     16,   0,   1,   0,   0,   0, 
     58,   0,  16,   0,   1,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0, 127,  67,   1,  64, 
      0,   0,   0,   0,   0,  63, 
     65,   0,   0,   5,  18,   0, 
     16,   0,   1,   0,   0,   0, 
     10,   0,  16,   0,   1,   0, 
      0,   0,   0,   0,   0,   7, 
     34,   0,  16,   0,   1,   0, 
      0,   0,  10,   0,  16,   0, 
      1,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0, 191, 
     49,   0,   0,   7,  34,   0, 
     16,   0,   1,   0,   0,   0, 
     26,   0,  16,   0,   1,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,  13,   0, 
      4,   3,  26,   0,  16,   0, 
      1,   0,   0,   0,  50,   0, 
      0,   9,  34,   0,  16,   0, 
      1,   0,   0,   0,  58,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
    127,  67,   1,  64,   0,   0, 
      0,   0,   0,  63,  65,   0, 
      0,   5,  34,   0,  16,   0, 
      1,   0,   0,   0,  26,   0, 
     16,   0,   1,   0,   0,   0, 
     49,   0,   0,  10, 194,   0, 
     16,   0,   1,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0, 128, 126,  67,   0,   0, 
      0,  63,   6,   4,  16,   0, 
      1,   0,   0,   0,  55,   0, 
      0,   9,  18,   0,  16,   0, 
      1,   0,   0,   0,  58,   0, 
     16,   0,   1,   0,   0,   0, 
     26,   0,  16,   0,   1,   0, 
      0,   0,  10,   0,  16,   0, 
      1,   0,   0,   0,  55,   0, 
      0,   9,  18,   0,  16,   0, 
      1,   0,   0,   0,  42,   0, 
     16,   0,   1,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
    127,  67,  10,   0,  16,   0, 
      1,   0,   0,   0,  52,   0, 
      0,   7, 130,   0,  16,   0, 
      0,   0,   0,   0,  58,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0, 128,   0, 
    128,  55,  14,  32,   0,   7, 
    114,   0,  16,   0,   0,   0, 
      0,   0,  70,   2,  16,   0, 
      0,   0,   0,   0, 246,  15, 
     16,   0,   0,   0,   0,   0, 
     50,   0,   0,   9, 130,   0, 
     16,   0,   0,   0,   0,   0, 
     10,  16,  16,   0,   3,   0, 
      0,   0,  10,   0,  16,   0, 
      1,   0,   0,   0,   1,  64, 
      0,   0,   0,   0, 254,  66, 
     56,   0,   0,   7, 130,   0, 
     16,   0,   0,   0,   0,   0, 
     58,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
    129, 128, 128,  59,   0,   0, 
      0,   7,  18,   0,  16,   0, 
      1,   0,   0,   0,  26,  16, 
     16,   0,   3,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
      0,  63,  28,   0,   0,   5, 
     18,   0,  16,   0,   1,   0, 
      0,   0,  10,   0,  16,   0, 
      1,   0,   0,   0,  85,   0, 
      0,   7,  34,   0,  16,   0, 
      1,   0,   0,   0,  10,   0, 
     16,   0,   1,   0,   0,   0, 
      1,  64,   0,   0,   6,   0, 
      0,   0,  31,   0,   4,   3, 
     26,   0,  16,   0,   1,   0, 
      0,   0,  50,   0,   0,   9, 
     66,   0,  16,   0,   1,   0, 
      0,   0,  10,  16,  16,   0, 
      2,   0,   0,   0,   1,  64, 
      0,   0, 249, 248, 248,  61, 
      1,  64,   0,   0,   0,   0, 
      0,  63,  27,   0,   0,   5, 
     66,   0,  16,   0,   1,   0, 
      0,   0,  42,   0,  16,   0, 
      1,   0,   0,   0,  36,   0, 
      0,   7,  66,   0,  16,   0, 
      1,   0,   0,   0,  42,   0, 
     16,   0,   1,   0,   0,   0, 
      1,  64,   0,   0,   0,   0, 
      0,   0,  37,   0,   0,   7, 
     66,   0,  16,   0,   1,   0, 
      0,   0,  42,   0,  16,   0, 
      1,   0,   0,   0,   1,  64, 
      0,   0,  31,   0,   0,   0, 
     32,   0,   0,   7, 130,   0, 
     16,   0,   1,   0,   0,   0, 
     26,   0,  16,   0,   1,   0, 
      0,   0,   1,  64,   0,   0, 
      1,   0,   0,   0,  55,   0, 
      0,  11, 114,   0,  16,   0, 
      2,   0,   0,   0, 246,  15, 
     16,   0,   1,   0,   0,   0, 
     70, 130,  32,   4,   0,   0, 
      0,   0,  42,   0,  16,   0, 
      1,   0,   0,   0,   6,  16, 
     16,   0,   2,   0,   0,   0, 
     54,   0,   0,   7, 114,   0, 
     16,   0,   3,   0,   0,   0, 
     70, 130,  32,   4,   0,   0, 
      0,   0,  42,   0,  16,   0, 
      1,   0,   0,   0,  18,   0, 
      0,   1,  54,   0,   0,   5, 
    114,   0,  16,   0,   2,   0, 
      0,   0,  70,  18,  16,   0, 
      2,   0,   0,   0,  54,   0, 
      0,   8, 114,   0,  16,   0, 
      3,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     21,   0,   0,   1,  50,   0, 
      0,  12, 114,   0,  16,   0, 
      0,   0,   0,   0,  70,   2, 
     16,   0,   2,   0,   0,   0, 
     70,   2,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0,   0,  63,   0,   0, 
      0,  63,   0,   0,   0,  63, 
      0,   0,   0,   0,  65,   0, 
      0,   5, 242,   0,  16,   0, 
      0,   0,   0,   0,  70,  14, 
     16,   0,   0,   0,   0,   0, 
     32,   0,   0,   7,  34,   0, 
     16,   0,   1,   0,   0,   0, 
     26,   0,  16,   0,   1,   0, 
      0,   0,   1,  64,   0,   0, 
      2,   0,   0,   0,   0,   0, 
      0,   7, 114,   0,  16,   0, 
      2,   0,   0,   0,  70,   2, 
     16,   0,   3,   0,   0,   0, 
     70,   2,  16,   0,   0,   0, 
      0,   0,  55,   0,   0,   9, 
    114,   0,  16,   0,   0,   0, 
      0,   0,  86,   5,  16,   0, 
      1,   0,   0,   0,  70,   2, 
     16,   0,   2,   0,   0,   0, 
     70,   2,  16,   0,   0,   0, 
      0,   0,  52,   0,   0,  10, 
    114,   0,  16,   0,   0,   0, 
      0,   0,  70,   2,  16,   0, 
      0,   0,   0,   0,   2,  64, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     51,   0,   0,  10, 114,   0, 
     16,   0,   0,   0,   0,   0, 
     70,   2,  16,   0,   0,   0, 
      0,   0,   2,  64,   0,   0, 
      0,   0, 127,  67,   0,   0, 
    127,  67,   0,   0, 127,  67, 
      0,   0,   0,   0,  56,   0, 
      0,  10, 114,  32,  16,   0, 
      0,   0,   0,   0,  70,   2, 
     16,   0,   0,   0,   0,   0, 
      2,  64,   0,   0, 129, 128, 
    128,  59, 129, 128, 128,  59, 
    129, 128, 128,  59,   0,   0, 
      0,   0,  51,   0,   0,   7, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  58,   0,  16,   0, 
      0,   0,   0,   0,   1,  64, 
      0,   0,   0,   0, 248,  65, 
     56,   0,   0,   7, 130,  32, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      8,  33,   4,  61,   1,   0, 
      0,   7,  18,   0,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   1,   0,   0,   0, 
      1,  64,   0,   0,  63,   0, 
      0,   0,  30,   0,   0,   7, 
     18,  32,  16,   0,   1,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,   1,  64, 
      0,   0, 128,   0,   0,   0, 
     62,   0,   0,   1,  83,  84, 
     65,  84, 116,   0,   0,   0, 
     44,   0,   0,   0,   4,   0, 
      0,   0,   0,   0,   0,   0, 
      5,   0,   0,   0,  21,   0, 
      0,   0,   5,   0,   0,   0, 
      2,   0,   0,   0,   2,   0, 
      0,   0,   1,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,   4,   0,   0,   0, 
      5,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0
};

#endif  /* PORT_GPU_RASTER_SHADERS_H */
